# Generated by Django 5.2.3 on 2025-07-13 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='answer_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setting', to='grader.answerkey'),
        ),
    ]
