# Generated by Django 5.2.3 on 2025-07-14 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0003_alter_setting_answer_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerkey',
            name='mark_per_question',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answerkey',
            name='total_marks',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
