# Generated by Django 5.2.3 on 2025-07-14 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0004_answerkey_mark_per_question_answerkey_total_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerkey',
            name='mark_per_question',
        ),
        migrations.RemoveField(
            model_name='answerkey',
            name='total_marks',
        ),
    ]
