# Generated by Django 5.2.3 on 2025-07-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0008_answerkey_mark_per_question_answerkey_total_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerkey',
            name='course_name',
            field=models.CharField(default='Default course name', max_length=50),
            preserve_default=False,
        ),
    ]
