# Generated by Django 5.2.3 on 2025-07-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0009_answerkey_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='student',
        ),
        migrations.AddField(
            model_name='submission',
            name='student_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='student_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
