# Generated by Django 5.2.3 on 2025-07-15 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0010_remove_submission_student_submission_student_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='student_name',
        ),
    ]
