# Generated by Django 5.2.3 on 2025-07-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0011_remove_submission_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='student_id',
            field=models.IntegerField(default=4211231199),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='student_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
