# Generated by Django 5.2.3 on 2025-07-15 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0012_submission_student_id_submission_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='grade',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
