# Generated by Django 5.2.3 on 2025-07-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0013_submission_grade_submission_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
